/**
 * View: Global Errors (Admin Only)
 */
ViewRouter.register('global-errors', {
  render: function(container) {
    container.innerHTML = '\
        <div class="stat-grid mb-xl">\
          <div class="stat-card"><div class="stat-card-icon red"><i class="fas fa-bug"></i></div><div class="stat-card-label">Total Error Groups</div><div class="stat-card-value" style="color:var(--accent-red)">12</div><div class="stat-card-trend down"><i class="fas fa-arrow-up"></i> 3 new today</div></div>\
          <div class="stat-card"><div class="stat-card-icon yellow"><i class="fas fa-building"></i></div><div class="stat-card-label">Affected Tenants</div><div class="stat-card-value">2<span style="font-size:0.9rem;color:var(--text-secondary)"> / 3</span></div><div class="stat-card-trend down"><i class="fas fa-arrow-up"></i> Gamma &amp; Acme</div></div>\
          <div class="stat-card"><div class="stat-card-icon blue"><i class="fas fa-clock"></i></div><div class="stat-card-label">Avg Resolution</div><div class="stat-card-value">4.2<span style="font-size:0.9rem;color:var(--text-secondary)">h</span></div><div class="stat-card-trend up"><i class="fas fa-arrow-down"></i> -18% improvement</div></div>\
        </div>\
        <div class="card">\
          <div class="card-header"><span class="card-title"><i class="fas fa-exclamation-triangle"></i> Cross-Tenant Error Groups</span><div style="display:flex;gap:var(--space-sm)"><span class="badge badge-critical">Unresolved 8</span><span class="badge badge-warning">Triaged 3</span><span class="badge badge-healthy">Resolved 1</span></div></div>\
          <div class="card-body" style="padding:0"><div class="table-container"><table>\
            <thead><tr><th></th><th>Error</th><th>Tenant</th><th>Service</th><th>Count</th><th>Trend</th><th>First Seen</th><th>Status</th><th>Action</th></tr></thead>\
            <tbody>\
              <tr><td><span class="dot dot-critical"></span></td><td><code class="mono" style="color:var(--accent-red);font-size:0.75rem">NullPointerException</code><br><span class="text-xs text-tertiary">OrderController.create(OrderController.java:142)</span></td><td class="text-sm">Acme Corp</td><td><span class="badge badge-info">order-service</span></td><td><span class="error-count-badge">1,247</span></td><td><span class="error-sparkline" style="color:var(--accent-red)">\u2582\u2583\u2585\u2587\u2587\u2588\u2587</span></td><td class="text-xs text-secondary">2h ago</td><td><span class="badge badge-critical">New</span></td><td><button class="btn btn-ghost text-xs" title="Jump to tenant errors"><i class="fas fa-external-link-alt"></i></button></td></tr>\
              <tr><td><span class="dot dot-critical"></span></td><td><code class="mono" style="color:var(--accent-red);font-size:0.75rem">ConnectionTimeoutException</code><br><span class="text-xs text-tertiary">RedisPool.getConnection(RedisPool.java:87)</span></td><td class="text-sm">Gamma Ltd</td><td><span class="badge badge-info">payment-svc</span></td><td><span class="error-count-badge">893</span></td><td><span class="error-sparkline" style="color:var(--accent-red)">\u2581\u2581\u2583\u2583\u2585\u2587\u2588</span></td><td class="text-xs text-secondary">45min ago</td><td><span class="badge badge-critical">New</span></td><td><button class="btn btn-ghost text-xs" title="Jump to tenant errors"><i class="fas fa-external-link-alt"></i></button></td></tr>\
              <tr><td><span class="dot dot-warning"></span></td><td><code class="mono" style="color:var(--accent-yellow);font-size:0.75rem">RateLimitExceeded</code><br><span class="text-xs text-tertiary">APIGateway.handleRequest(Gateway.java:55)</span></td><td class="text-sm">Beta Inc</td><td><span class="badge badge-info">api-gateway</span></td><td><span class="error-count-badge" style="background:rgba(210,153,34,0.15);color:var(--accent-yellow)">156</span></td><td><span class="error-sparkline">\u2583\u2583\u2585\u2583\u2582\u2581\u2581</span></td><td class="text-xs text-secondary">1d ago</td><td><span class="badge badge-warning">Triaged</span></td><td><button class="btn btn-ghost text-xs" title="Jump to tenant errors"><i class="fas fa-external-link-alt"></i></button></td></tr>\
              <tr><td><span class="dot dot-critical"></span></td><td><code class="mono" style="color:var(--accent-red);font-size:0.75rem">OutOfMemoryError</code><br><span class="text-xs text-tertiary">InventorySync.batchUpdate(InventorySync.java:203)</span></td><td class="text-sm">Acme Corp</td><td><span class="badge badge-info">inventory-svc</span></td><td><span class="error-count-badge">67</span></td><td><span class="error-sparkline" style="color:var(--accent-red)">\u2581\u2581\u2581\u2583\u2587\u2588\u2587</span></td><td class="text-xs text-secondary">30min ago</td><td><span class="badge badge-critical">New</span></td><td><button class="btn btn-ghost text-xs" title="Jump to tenant errors"><i class="fas fa-external-link-alt"></i></button></td></tr>\
              <tr style="opacity:0.5"><td><span class="dot dot-healthy"></span></td><td><code class="mono" style="color:var(--accent-green);font-size:0.75rem;text-decoration:line-through">SocketException</code><br><span class="text-xs text-tertiary">HttpClient.send(HttpClient.java:44)</span></td><td class="text-sm">Gamma Ltd</td><td><span class="badge badge-info">user-auth</span></td><td><span class="error-count-badge" style="background:rgba(63,185,80,0.15);color:var(--accent-green)">0</span></td><td><span class="error-sparkline">\u2587\u2585\u2583\u2582\u2581\u2581\u2581</span></td><td class="text-xs text-secondary">3d ago</td><td><span class="badge badge-healthy">Resolved</span></td><td><button class="btn btn-ghost text-xs" title="View details"><i class="fas fa-eye"></i></button></td></tr>\
            </tbody>\
          </table></div></div>\
        </div>';
  }
});
