// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package lifecycle

import (
	"context"
	"sync"
	"testing"
	"time"

	"go.uber.org/zap"
	"go.uber.org/zap/zaptest"
)

// ═══════════════════════════════════════════════════
// Mock implementations for distributed purge testing
// ═══════════════════════════════════════════════════

// mockDistPurger implements LifecyclePurger + IndexLister + SingleIndexPurger
// for testing the distributed purge pipeline.
type mockDistPurger struct {
	mu             sync.Mutex
	expiredIndices map[SignalType][]string
	deletedIndices []string
	deleteErr      error
}

var _ LifecyclePurger = (*mockDistPurger)(nil)
var _ IndexLister = (*mockDistPurger)(nil)
var _ SingleIndexPurger = (*mockDistPurger)(nil)

func newMockDistPurger(expired map[SignalType][]string) *mockDistPurger {
	return &mockDistPurger{
		expiredIndices: expired,
	}
}

func (m *mockDistPurger) PurgeExpired(_ context.Context, signal SignalType, _ time.Time) (*PurgeResult, error) {
	return &PurgeResult{Signal: signal, DeletedDocs: 0, DeletedUnits: 0}, nil
}

func (m *mockDistPurger) PurgeByApp(_ context.Context, _ string, signal SignalType, _ time.Time) (*PurgeResult, error) {
	return &PurgeResult{Signal: signal}, nil
}

func (m *mockDistPurger) EstimatePurge(_ context.Context, signal SignalType, _ time.Time) (*PurgeEstimate, error) {
	return &PurgeEstimate{Signal: signal}, nil
}

func (m *mockDistPurger) GetDataBoundary(_ context.Context, signal SignalType) (*DataBoundary, error) {
	return &DataBoundary{Signal: signal, IsEmpty: true}, nil
}

func (m *mockDistPurger) ListExpired(_ context.Context, signal SignalType, _ time.Time) ([]string, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.expiredIndices[signal], nil
}

func (m *mockDistPurger) DeleteSingleIndex(_ context.Context, indexName string) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	if m.deleteErr != nil {
		return m.deleteErr
	}
	m.deletedIndices = append(m.deletedIndices, indexName)
	return nil
}

func (m *mockDistPurger) GetDeletedIndices() []string {
	m.mu.Lock()
	defer m.mu.Unlock()
	result := make([]string, len(m.deletedIndices))
	copy(result, m.deletedIndices)
	return result
}

// mockDistResolver implements RetentionResolver for tests.
type mockDistResolver struct {
	retention time.Duration
}

func (r *mockDistResolver) Resolve(_ context.Context, _ SignalType, _ string) (EffectiveRetention, error) {
	return EffectiveRetention{Duration: r.retention, Source: SourcePlatformDefault}, nil
}

func (r *mockDistResolver) ResolveAll(_ context.Context, _ string) (map[SignalType]EffectiveRetention, error) {
	result := make(map[SignalType]EffectiveRetention)
	for _, s := range AllSignals() {
		result[s] = EffectiveRetention{Duration: r.retention, Source: SourcePlatformDefault}
	}
	return result, nil
}

// mockAuditCollector collects audit events for assertion.
type mockAuditCollector struct {
	mu     sync.Mutex
	events []LifecycleEvent
}

func (a *mockAuditCollector) Emit(_ context.Context, event LifecycleEvent) {
	a.mu.Lock()
	defer a.mu.Unlock()
	a.events = append(a.events, event)
}

func (a *mockAuditCollector) GetEvents() []LifecycleEvent {
	a.mu.Lock()
	defer a.mu.Unlock()
	result := make([]LifecycleEvent, len(a.events))
	copy(result, a.events)
	return result
}

// ═══════════════════════════════════════════════════
// Test Cases (Engine-based distributed purge)
// ═══════════════════════════════════════════════════

// Note: Full distributed purge integration tests are in engine_adapter_test.go
// which tests the DistributedPurgeOrchestrator with mock engines.
// The tests below verify scheduler-level configuration behaviors.

func TestScheduler_RunCycle_SingleNodeWhenNoOrchestrator(t *testing.T) {
	// Without orchestrator (engine), distributed=true falls back to single-node
	purger := newMockDistPurger(map[SignalType][]string{
		SignalTrace: {"idx1", "idx2"},
	})

	s := NewScheduler(
		WithResolver(&mockDistResolver{retention: 7 * 24 * time.Hour}),
		WithPurger(purger),
		// No WithEngine — single-node mode
		WithConfig(SchedulerConfig{
			Enabled:              true,
			Interval:             time.Hour,
			Distributed:          true, // even with Distributed=true, no engine → single-node
			DistributedThreshold: 1,
			NodeID:               "test-node-1",
		}),
		WithLogger(zaptest.NewLogger(t)),
	)

	ctx := context.Background()
	s.runCycle(ctx)

	// In single-node mode, DeleteSingleIndex is NOT called (PurgeExpired is used)
	deleted := purger.GetDeletedIndices()
	if len(deleted) != 0 {
		t.Errorf("expected 0 DeleteSingleIndex calls in single-node mode, got %d", len(deleted))
	}
}

func TestNewScheduler_NodeID_FromConfig(t *testing.T) {
	s := NewScheduler(
		WithConfig(SchedulerConfig{NodeID: "my-custom-node"}),
		WithLogger(zap.NewNop()),
	)

	if s.nodeID != "my-custom-node" {
		t.Errorf("expected nodeID=my-custom-node, got %s", s.nodeID)
	}
}

func TestNewScheduler_NodeID_AutoGenerated(t *testing.T) {
	s := NewScheduler(
		WithConfig(SchedulerConfig{}),
		WithLogger(zap.NewNop()),
	)

	if s.nodeID == "" {
		t.Error("expected auto-generated nodeID, got empty string")
	}
	if len(s.nodeID) < 5 {
		t.Errorf("expected meaningful nodeID, got %s", s.nodeID)
	}
}
